from enum import Enum
from typing import List
from datetime import datetime, timedelta
from pydantic import BaseModel, Field, conint, confloat, validator

# ---------- Category (Enum1) ----------


class Category(str, Enum):
    UPS_SYSTEMS = "UPS Systems"
    GENERATOR_FUEL_SYSTEMS = "Generator & Fuel Systems"
    SWITCHGEAR_DISTRIBUTION = "Switchgear & Distribution"
    CHILLERS_COOLING_PLANTS = "Chillers & Cooling Plants"
    CRAC_CRAH_UNITS = "CRAC/CRAH Units"
    FIRE_SYSTEMS = "Fire Systems"
    CABLING_CONTROLS = "Cabling & Controls"
    SUSTAINABILITY = "Sustainability"


# ---------- Priority ----------


class Priority(str, Enum):
    P0 = "P0"  # Critical
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    P5 = "P5"  # Lowest


# ---------- Risk Level ----------


class RiskLevel(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


# ---------- Impact Areas ----------


class ImpactArea(str, Enum):
    OPERATIONS = "operations"
    FINANCE = "finance"
    SAFETY = "safety"
    CLIENT = "client"
    SUSTAINABILITY = "sustainability"
    STRATEGIC = "strategic"  # normalized spelling


# Example: build mapping from your enum2 JSON at startup.
ENUM2 = [
    {"id": 1, "matrix": "load", "name": "kW"},
    {"id": 2, "matrix": "load", "name": "MW"},
    # ...
    {"id": 74, "matrix": "hvac", "name": "RT"},
]

MATRIX_UNIT_TO_ID = {(e["matrix"], e["name"]): e["id"] for e in ENUM2}


def resolve_capacity_enum2_id(matrix_type: str, unit_name: str) -> int:
    try:
        return MATRIX_UNIT_TO_ID[(matrix_type, unit_name)]
    except KeyError:
        raise ValueError(
            f"Invalid capacity pair: matrix_type={matrix_type}, unit_name={unit_name}"
        )


PRIORITY_TO_START_OFFSET_DAYS = {
    Priority.P0: 1,  # critical
    Priority.P1: 7,
    Priority.P2: 30,
    Priority.P3: 90,
    Priority.P4: 120,
    Priority.P5: 180,  # lowest priority ~ 6 months
}


class RequiredCapacity(BaseModel):
    matrix_type: str = Field(
        ...,
        description=(
            "One of: load, fuel, power, energy, capacity, cooling, heating, "
            "water, steam, compressed_air, gas, hvac"
        ),
    )
    unit_name: str = Field(
        ...,
        description="Must match the 'name' field from enum2 (e.g. 'kW', 'tons', 'm³').",
    )
    value: confloat(ge=0) = Field(
        ..., description="Numeric value for required capacity in the chosen unit."
    )


class ProjectIntentLLM(BaseModel):
    category: Category
    required_capacity: RequiredCapacity

    priority: Priority
    scope_of_works: str = Field(
        ...,
        description="Short enhanced description of the scope of works, ~150-200 words.",
    )

    risk_level: RiskLevel
    impact_areas: List[ImpactArea]

    equipment_survivability_days: conint(ge=0) = Field(
        ...,
        description="Number of days the existing system can survive without this project.",
    )

    expected_project_duration_days: conint(ge=1, le=3650) = Field(
        ...,
        description="Estimated number of days required to complete the project once started.",
    )


class ProjectAutoGenerated(BaseModel):
    # LLM-derived semantic fields
    category: Category
    required_capacity_matrix_type: str
    required_capacity_unit_name: str
    required_capacity_value: float
    required_capacity_enum2_id: int  # derived from matrix_type + unit_name

    priority: Priority
    scope_of_works: str
    risk_level: RiskLevel
    impact_areas: List[ImpactArea]

    equipment_survivability_days: int
    expected_project_duration_days: int

    # System-derived deterministic fields
    project_start: datetime
    project_end: datetime
