# app/graphs/nodes/action_executor_node.py

import logging
from typing import Dict, Any

from app.controllers.tool_impl import (
    send_email_via_api,
    export_file_via_api,
    notify_via_api,
    create_record_via_api,
    save_generic_via_api,
    webhook_call_via_api
)

log = logging.getLogger("graph>node>action_executor")


async def action_executor_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generic executor for ANY post-action generated by the planner.

    Handles actions like:
    - email
    - export / download
    - notify
    - create
    - save
    - webhook
    - slack / teams / sms / whatsapp (via notify)
    - ANY future action

    Planner stores:
      state["plan"]["post_actions"] = [
         { "type": "email", "params": {"to": "..."} },
         { "type": "export", "params": {"format": "excel"} },
         ...
      ]

    Dispatcher runs through these one by one.
    """
    plan = state.get("plan", {})
    post_actions = plan.get("post_actions", [])

    if not post_actions:
        log.info("No post-actions left.")
        state["response"] = state.get("response", "All actions complete.")
        return state

    # Take FIRST action in the list (FIFO)
    action = post_actions.pop(0)
    state["plan"]["post_actions"] = post_actions  # save remaining actions

    action_type = action.get("type")
    params = action.get("params", {}) or {}

    log.info(f"Executing post-action: {action_type} with params: {params}")

    # -----------------------------------------------
    # ACTION: EMAIL
    # -----------------------------------------------
    if action_type == "email":
        email_to = params.get("to") or state.get("email_to")
        if not email_to:
            log.warning("Email action requested, but no email_to address found.")
            state["email_sent"] = False
            return state

        try:
            await send_email_via_api(email_to, state)
            state["email_sent"] = True
        except Exception as e:
            log.exception("Email sending failed: %s", e)
            state["email_sent"] = False
        return state

    # -----------------------------------------------
    # ACTION: EXPORT / DOWNLOAD
    # -----------------------------------------------
    if action_type in {"export", "download"}:
        file_format = params.get("format", "excel")

        try:
            export_path = await export_file_via_api(format=file_format, state=state)
            state["exported"] = True
            state["export_path"] = export_path
        except Exception as e:
            log.exception("Export failed: %s", e)
            state["exported"] = False

        return state

    # -----------------------------------------------
    # ACTION: NOTIFY (Slack, Teams, SMS, WhatsApp, email-based)
    # -----------------------------------------------
    if action_type == "notify":
        channel = params.get("channel", "app")
        message = params.get("message", "Your action has completed.")
        try:
            await notify_via_api(channel=channel, message=message, state=state)
            state["notified"] = True
        except Exception as e:
            log.exception("Notify action failed: %s", e)
            state["notified"] = False
        return state

    # -----------------------------------------------
    # ACTION: CREATE (create tickets, WRs, records…)
    # -----------------------------------------------
    if action_type == "create":
        try:
            result = await create_record_via_api(params)
            state["create_result"] = result
            state["created"] = True
        except Exception as e:
            log.exception("Create action failed: %s", e)
            state["created"] = False
        return state

    # -----------------------------------------------
    # ACTION: SAVE (save results somewhere)
    # -----------------------------------------------
    if action_type == "save":
        try:
            result = await save_generic_via_api(params, state)
            state["save_result"] = result
            state["saved"] = True
        except Exception as e:
            log.exception("Save action failed: %s", e)
            state["saved"] = False
        return state

    # -----------------------------------------------
    # ACTION: WEBHOOK
    # -----------------------------------------------
    if action_type == "webhook":
        url = params.get("url")
        if not url:
            log.warning("Webhook requested but no URL provided.")
            state["webhook_called"] = False
            return state

        try:
            await webhook_call_via_api(url, params=params, state=state)
            state["webhook_called"] = True
        except Exception as e:
            log.exception("Webhook call failed: %s", e)
            state["webhook_called"] = False
        return state

    # -----------------------------------------------
    # FALLBACK: ANY FUTURE ACTION
    # -----------------------------------------------
    log.warning(f"Unknown action '{action_type}', marking as executed.")
    state[f"action_{action_type}_executed"] = True
    return state
